//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peko_Jump {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Peko_Jump.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources/audio/.
        /// </summary>
        internal static string audio {
            get {
                return ResourceManager.GetString("audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/StarChoco-rgovx.ttf.
        /// </summary>
        internal static string font {
            get {
                return ResourceManager.GetString("font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources/images/.
        /// </summary>
        internal static string images {
            get {
                return ResourceManager.GetString("images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HighScore: {0}.
        /// </summary>
        internal static string MaxScore {
            get {
                return ResourceManager.GetString("MaxScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources/OpenSans.ttf.
        /// </summary>
        internal static string opensans {
            get {
                return ResourceManager.GetString("opensans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peko Jump.
        /// </summary>
        internal static string PekoJump {
            get {
                return ResourceManager.GetString("PekoJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presents.
        /// </summary>
        internal static string Presents {
            get {
                return ResourceManager.GetString("Presents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &quot;B&quot; to return to Menu.
        /// </summary>
        internal static string PressBToReturnToMenu {
            get {
                return ResourceManager.GetString("PressBToReturnToMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &quot;R&quot; to restart.
        /// </summary>
        internal static string PressRToRestart {
            get {
                return ResourceManager.GetString("PressRToRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press SPACE to start.
        /// </summary>
        internal static string PressSpaceToStart {
            get {
                return ResourceManager.GetString("PressSpaceToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score: {0}.
        /// </summary>
        internal static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
    }
}
